#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
def hourglassSum(arr):
    row = len(arr)
    column = len(arr[0])
    #set maxVal to something so small that values given have to be larger
    maxVal = -9999999999999
    miniSum=0
    t = 0
    for i in range(row-2):
        for j in range(column-2):
            miniSum = arr[i][j]+arr[i][j+1]+arr[i][j+2]+arr[i+1][j+1]+arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2]
            if miniSum > maxVal:
                maxVal = miniSum
                miniSum=0
    return maxVal                    
                
    
   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
